# Generated by Django 3.1.3 on 2020-12-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asso_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.ManyToManyField(to='filters.Category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filters.department')),
            ],
            options={
                'db_table': 'association',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('year_of_birth', models.IntegerField()),
                ('asso', models.ManyToManyField(to='login.Association')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filters.department')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('registration_date', models.DateField()),
                ('asso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.association')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
            options={
                'db_table': 'account',
                'managed': True,
            },
        ),
    ]
