# Generated by Django 3.1.3 on 2021-01-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20201230_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='asso',
            field=models.ManyToManyField(blank=True, to='login.Association'),
        ),
    ]
