# Generated by Django 3.1.3 on 2021-01-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20210113_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='asso_name',
        ),
        migrations.AddField(
            model_name='association',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='association',
            name='logo',
            field=models.URLField(max_length=1000, null='img\\Harmony.png'),
            preserve_default='img\\Harmony.png',
        ),
        migrations.AddField(
            model_name='association',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='association',
            name='website',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
