# Generated by Django 3.1.3 on 2021-01-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210113_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='approved',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='association',
            name='logo',
            field=models.URLField(max_length=1000, null='img/Harmony.png'),
        ),
    ]
