# Generated by Django 3.1.3 on 2021-01-25 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0006_auto_20210113_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='asso',
        ),
        migrations.AddField(
            model_name='association',
            name='member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
