# Generated by Django 3.1.3 on 2020-12-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filters', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('approved', models.BooleanField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.account')),
                ('category', models.ManyToManyField(to='filters.Category')),
            ],
            options={
                'db_table': 'tip',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=150)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('posting_date', models.DateField()),
                ('approved', models.BooleanField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.account')),
                ('category', models.ManyToManyField(to='filters.Category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filters.department')),
            ],
            options={
                'db_table': 'image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('approved', models.BooleanField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.account')),
                ('category', models.ManyToManyField(to='filters.Category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filters.department')),
            ],
            options={
                'db_table': 'event',
                'managed': True,
            },
        ),
    ]
