# Generated by Django 3.1.2 on 2020-12-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='account',
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='department',
        ),
        migrations.RemoveField(
            model_name='image',
            name='account',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='account',
        ),
    ]
