# Generated by Django 3.1.2 on 2020-12-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201228_1205'),
        ('content', '0002_auto_20201228_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login.userdata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tip',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login.userdata'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
