# Generated by Django 3.1.3 on 2021-01-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20210113_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='posting_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
