# Generated by Django 3.1.3 on 2021-01-14 16:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210113_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
