# Generated by Django 3.1.3 on 2021-01-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_tip_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
