# Generated by Django 3.1.2 on 2020-12-30 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0002_region_region_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'managed': True, 'verbose_name': 'Pays', 'verbose_name_plural': 'Pays'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'managed': True, 'verbose_name': 'Departement', 'verbose_name_plural': 'Departements'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': True, 'verbose_name': 'Région', 'verbose_name_plural': 'Régions'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filters.category'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_code',
            field=models.IntegerField(),
        ),
    ]
