# Generated by Django 3.1.3 on 2021-01-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0004_auto_20210118_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'managed': True, 'ordering': ['department_code'], 'verbose_name': 'Departement', 'verbose_name_plural': 'Departements'},
        ),
    ]
